name: SPOT-6-7

label_mapping:
  invalid_pixel: 0
  sealed_soil: 1
  non_sealed_soil: 2

band_names:
  - red
  - green
  - blue
  - nir

wavelengths:
  - 0.660   # red
  - 0.560   # green
  - 0.485   # blue
  - 0.825   # nir

scale_factor: 10000.0
bit_depth: 16

nodata_value: 0
gsd_m: 1.5
tile_size_px: [512, 512]

rgbnir_idx:
  - 0   # red
  - 1   # green
  - 2   # blue
  - 3   # nir